[package]
name = "fluxtream"
version = "1.0.0"
authors = []

[addresses]
self="0xcfb4348624dc4c16cbdac455e7302e7b2a7b9f7402627405df0842a04c467100"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
